// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// rList
Rcpp::List rList(Rcpp::NumericMatrix m, int niter);
RcppExport SEXP _bam_rList(SEXP mSEXP, SEXP niterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type niter(niterSEXP);
    rcpp_result_gen = Rcpp::wrap(rList(m, niter));
    return rcpp_result_gen;
END_RCPP
}
// permute_matrix
Rcpp::NumericMatrix permute_matrix(Rcpp::NumericMatrix m, int niter);
RcppExport SEXP _bam_permute_matrix(SEXP mSEXP, SEXP niterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type niter(niterSEXP);
    rcpp_result_gen = Rcpp::wrap(permute_matrix(m, niter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bam_rList", (DL_FUNC) &_bam_rList, 2},
    {"_bam_permute_matrix", (DL_FUNC) &_bam_permute_matrix, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_bam(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
