# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rList <- function(m, niter) {
    .Call('_bam_rList', PACKAGE = 'bam', m, niter)
}

permute_matrix <- function(m, niter) {
    .Call('_bam_permute_matrix', PACKAGE = 'bam', m, niter)
}

